#!/bin/bash

scr="test_word.py"
model="w_medium_200dim_5gradclip_0.0001reg"

cp model/$model/settings.txt settings.py

for i in {2..20}; do
    python $scr data/acl/medium_500_19K/10K_combined_val model/$model/ result/$model/ $i
    echo -e "${i}\n" >> logs/${model}_validation_errors.log
    python eval.py result/$model/ model/$model/ >> logs/${model}_validation_errors.log
done
